ENT.Base 			= "npc_vj_recb_crimsonhead"
ENT.Type 			= "ai"
ENT.PrintName 		= "Crimsonhead"
ENT.Author 			= "Darkborn"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category        = "Resident Evil: Cold Blood"