ENT.Base = "npc_vj_creature_base"
ENT.Type = "ai"
ENT.PrintName = "Spider (Small)"
ENT.Author = "Darkborn"
ENT.Contact = "http://steamcommunity.com/groups/vrejgaming"
ENT.Category = "Resident Evil: Cold Blood"
